const actionTypes = Object.freeze({
  //app
  APP_START_UP_COMPLETE: "APP_START_UP_COMPLETE",
  SET_CONTENT_OF_CONFIRM_MODAL: "SET_CONTENT_OF_CONFIRM_MODAL",

  //user
  ADD_USER_SUCCESS: "ADD_USER_SUCCESS",

  USER_LOGIN_SUCCESS: " USER_LOGIN_SUCCESS",
  USER_LOGIN_FAIL: "USER_LOGIN_FAIL",
  PROCESS_LOGOUT: "PROCESS_LOGOUT",

  FETCH_ALL_USER_SUCCESS: "FETCH_ALL_USER_SUCCESS",
  FETCH_ALL_USER_FAILED: "FETCH_ALL_USER_FAILED",

  FETCH_ALL_VIEW_SUCCESS: "FETCH_ALL_VIEW_SUCCESS",
  FETCH_ALL_VIEW_FAILED: "FETCH_ALL_VIEW_FAILED",

  CREATE_USER_SUCCESS: "CREATE_USER_SUCCESS",
  CREATE_USER_FAILED: "CREATE_USER_FAILED",

  EDIT_USER_SUCCESS: "EDIT_USER_SUCCESS",
  EDIT_USER_FAILED: "EDIT_USER_FAILED",

  DELETE_USER_SUCCESS: "DELETE_USER_SUCCESS",
  DELETE_USER_FAILED: "DELETE_USER_FAILED",

  //view
  CREATE_VIEW_SUCCESS: "CREATE_VIEW_SUCCESS",
  CREATE_VIEW_FAILED: "CREATE_VIEW_FAILED",

  //order
  CREATE_ORDER_SUCCESS: "CREATE_ORDER_SUCCESS",
  CREATE_ORDER_FAILED: "CREATE_ORDER_FAILED",

  DELETE_ORDER_SUCCESS: "DELETE_ORDER_SUCCESS",
  DELETE_ORDER_FAILED: "DELETE_ORDER_FAILED",

  FETCH_ALL_ORDER_SUCCESS: "FETCH_ALL_ORDER_SUCCESS",
  FETCH_ALL_ORDER_FAILED: "FETCH_ALL_ORDER_FAILED",

  //book
  CREATE_BOOK_SUCCESS: "CREATE_BOOK_SUCCESS",
  CREATE_BOOK_FAILED: "CREATE_BOOK_FAILED",

  EDIT_BOOK_SUCCESS: "EDIT_BOOK_SUCCESS",
  EDIT_BOOK_FAILED: "EDIT_BOOK_FAILED",

  DELETE_BOOK_SUCCESS: "DELETE_BOOK_SUCCESS",
  DELETE_BOOK_FAILED: "DELETE_BOOK_FAILED",

  FETCH_ALL_BOOK_SUCCESS: "FETCH_ALL_BOOK_SUCCESS",
  FETCH_ALL_BOOK_FAILED: "FETCH_ALL_BOOK_FAILED",
});

export default actionTypes;
